---
name: "SLURM"
partition: "cpuonly"
job-name: "box_random_seq_entire"
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 152
time: 4000 #600 for 10 hours
scheduler: cpu_distribute
cpus_per_rep: 38


experiment_copy_src:
  - "../" # RL Code base
experiment_copy_auto_dst: "../../CODE_COPY/"
---
name: box_random_seq_entire
import_path: "./shared_dense_segmenting_vars.yaml"
import_exp: "box_random_seq_entire"

# cw2 config
repetitions: 4      # Number of repetitions, each with different random seed, 2 [for hyper paremtertuning 2] or 4 for test, 20 for paper
reps_per_job: 4     # job id assigment
reps_in_parallel: 4 #jobs run in parallel = # of gpus used
iterations: &iterations 35000
num_checkpoints: 1

# Hardware specific parameters
params:
  sampler:
    args:
      num_env_train: 4
      num_env_test: 38
      episodes_per_train_env: 1
      episodes_per_test_env: 4
  projection:
    args:
      total_train_steps: *iterations

list:
  reference_split:
    q_loss_strategy: ["enforce_no_overlap_overconf", "enforce_no_overlap_trunc", "enforce_no_overlap_trunc"]
    v_func_estimation: ["enforce_no_overlap_overconf", "enforce_no_overlap_overconf", "enforce_no_overlap_trunc"]