---
name: "SLURM"
partition: "cpuonly"
job-name: "metaworld_seq_entire"
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 152
time: 4000 #600 for 10 hours
scheduler: cpu_distribute
cpus_per_rep: 38

experiment_copy_src:
  - "../" # RL Code base
experiment_copy_auto_dst: "../../CODE_COPY/"
---
name: metaworld_seq_entire
import_path: "./shared_meta.yaml"
import_exp: "metaworld_seq_entire"

# cw2 config
repetitions: 4      # Number of repetitions, each with different random seed, 4 for test, 20 for paper
reps_per_job: 4
reps_in_parallel: 4
iterations: &iterations 20000
num_checkpoints: 1

# Hardware specific parameters
params:
  projection:
    args:
      total_train_steps: *iterations
  sampler:
    args:
      num_env_train: 2
      num_env_test: 38
      episodes_per_train_env: 1
      episodes_per_test_env: 4

grid:
  reference_split:
    n_splits: [2, 3, 4, 5, 6]
  sampler:
    args:
      env_id:
        [
          "metaworld_ProDMP_TCE/assembly-v2",
          "metaworld_ProDMP_TCE/hammer-v2",
          "metaworld_ProDMP_TCE/button-press-v2",
          "metaworld_ProDMP_TCE/disassemble-v2",
          "metaworld_ProDMP_TCE/hand-insert-v2"
        ]